config/routes.rb
Rails.application.routes.draw do
  get 'event_entries/create'

  resources :events, only: %i[index show] do
    resource :event_entry, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  extend RDL::Annotate
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  # カラムの情報(Event#id)等が追加される
  extend ActiveRecord::Associations::ClassMethods
  extend ActiveRecord::ModelSchema::ClassMethods

  has_many :event_entries

  type '() -> Integer', typecheck: :later
  def hoge
    10
  end

  type '() -> self', typecheck: :later
  def self.first_event
    Event.first
  end
end

app/models/event_entry.rb
class EventEntry < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_entries
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  extend RDL::Annotate
  protect_from_forgery with: :exception

  protected
  type '() -> User'
  def current_user
    User.first
  end
end

app/controllers/event_entries_controller.rb
class EventEntriesController < ApplicationController
  def create
    Event.find(params[:event_id]).event_entries.create(user: current_user)
    redirect_to :events
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    RDL.var_type :@events, 'Array<Event>', typecheck: :later
    @events = Event.all
  end

  def show
    RDL.var_type :@event, 'Event', typecheck: :later
    @event = Event.find(params[:id])
    RDL.var_type :@event_entry, 'EventEntry', typecheck: :later
    @event_entry = @event.event_entries.build
    RDL.var_type :@entry_count, 'Integer', typecheck: :later
    @entry_count = @event.event_entries.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event do %>
        <% "#{event.id}: #{event.title}" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>参加人数: <%= @entry_count %></p>
<%= form_for :event_entry, url: event_event_entry_path(@event, @event_entry) do |f| %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RdlDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>